version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: ../logs/pyquanttrader.log
    maxBytes: 10485760  # 10MB
    backupCount: 30
    encoding: utf8
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: ../logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8
root:
  level: INFO
  handlers: [console, file, error_file]